global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 30s
  scrape_configs:
  - job_name: router
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /
    scheme: http
    static_configs:
    - targets:
      - localhost:8888